spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: transaction-management
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: b2b
server:
  port: 8081

transaction:
  rabbit:
    queue-name: transaction-queue
    exchange-name: transaction-exchange
    routing-key: transaction-routing
    dead-letter-routing-key: dead-letter-routing
    dead-letter-exchange: transaction-dead-letter-exchange
    dead-letter-queue-name: transaction-dead-letter-queue
